// <auto-generated />
using ConstribuyenteApi.Contribuyente.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConstribuyenteApi.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20251103042640_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("ConstribuyenteApi.Contribuyente.Models.Contribuyentes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cedula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("fechaRegistro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Contribuyentes");

                    b.HasData(
                        new
                        {
                            id = 1,
                            cedula = "40233012394",
                            direccion = "Madre Vieja",
                            email = "johanes384@gmail.com",
                            fechaRegistro = "2025-01-16",
                            nombre = "Johan",
                            telefono = "8046559632"
                        },
                        new
                        {
                            id = 2,
                            cedula = "40233345675",
                            direccion = "Cotui",
                            email = "mvillatapia384@gmail.com",
                            fechaRegistro = "2025-01-16",
                            nombre = "Malvin",
                            telefono = "8296559632"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
